-- AlterTable
ALTER TABLE `baseline_items` ADD COLUMN `modalidad` ENUM('PRECIOS_UNITARIOS', 'SUMA_ALZADA', 'ALCANCE') NOT NULL DEFAULT 'PRECIOS_UNITARIOS';

-- AlterTable
ALTER TABLE `wbs_items` ADD COLUMN `modalidad` ENUM('PRECIOS_UNITARIOS', 'SUMA_ALZADA', 'ALCANCE') NOT NULL DEFAULT 'PRECIOS_UNITARIOS';
